default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: mudassir_nazir
  password: 1234

development:
  <<: *default
  database: recipe_rails_development


test:
  <<: *default
  database: recipe_rails_test

production:
  <<: *default
  database: recipe_rails__production